---
# tasks file for vault
- name: Instala vault via dnf
  dnf:
    state: latest
    update_cache: true
    name: 
      - dnf-plugins-core
      - vault
      - ca-certificates
  register: dnf_install

- name: Configuração vault.hcl
  template:
    src: '{{ filename }}.j2'
    dest: /etc/vault.d/{{ filename }}
    owner: vault
    group: vault
    mode: '0644'
  loop:
    - vault.hcl
    - vault.env
  loop_control: 
    loop_var: filename

- name: Configuração vault.env
  template:
    src: vault.env.j2
    dest: /etc/vault.d/vault.env
    owner: vault
    group: vault
    mode: '0644'

- name: Copia o certificado SSL
  copy:
    src: "ssl/"
    dest: /opt/vault/tls/
    owner: vault
    group: vault
    mode: '0600'

- name: Inicia/Reinicia o vault
  service:
    name: vault
    state: restarted
    enabled: true

- name: Insere as váriaveis de ambiente
  lineinfile:
    path: /etc/profile
    line: export VAULT_ADDR='http://{{ ansible_default_ipv4.address }}:8200'
  