---
- hosts: all
  vars_files:
    - hostname.yml
  pre_tasks:
    - name: Download repo hashcorp
      get_url:
        url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
        dest: /etc/yum.repos.d/hashcorp.repo
        mode: '6440'
    
  roles:  
    - consul
    - vault
  
  tasks:
    - name: consul members
      debug:
        msg: "{{ consul_members.stdout_lines }}"
    
    - name: acessos consul
      debug:
        msg: 
          - "http://{{ ansible_default_ipv4.address }}:8500"
      when: ansible_hostname | regex_search("consul")
    
    - name: acessos vault
      debug:
        msg: 
          - "http://{{ ansible_default_ipv4.address }}:8200"
      when: ansible_hostname | regex_search("vault")
